[package]
name = "aurora-compositor"
description = "Aurora OS — compositor Wayland"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "aurora"
path = "src/main.rs"

[dependencies]
smithay = { workspace = true, features = [
    "backend_winit",
    "backend_egl",
    "renderer_gl",
    "wayland_frontend",
    "desktop",
    "use_system_lib",
] }
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true